## Pandas DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures:
- Series (One-dimensional array-like object)
- DataFrame (Two-dimensional, size-mutable and potentially heterogeneous tabular data structure with labeled indexes)

In [75]:
!pip install pandas

In [76]:
import pandas as pd

### Series
A pandas series is a one-dimensional array-like object that can hold any data type. It is similar to a column in the table.

In [77]:
# Converting a list into series
data = [1,2,3,4,5,6]
series = pd.Series(data)

print(f"Pandas series is : \n{series}")
print(f"\nData type of pandas series is : {type(series)}")

Pandas series is :
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

Data type of pandas series is : <class 'pandas.Series'>

In [78]:
# Converting a dictionary into series
data = {'a':1 , 'b':2 , 'c':3 , 'd': 4}
series = pd.Series(data)

print(f"Series obtained from dictionary is : \n{series}")

Series obtained from dictionary is :
a    1
b    2
c    3
d    4
dtype: int64

In [79]:
# Combining data and index lists
data= [10,20,30,40]
index = ['a','b','c','d']

series = pd.Series(data,index = index)
print(f"List {data} indexed with {index} is : \n{series}")

List [10, 20, 30, 40] indexed with ['a', 'b', 'c', 'd'] is :
a    10
b    20
c    30
d    40
dtype: int64

### DataFrame

In [80]:
# Creating a dataframe from a dictionary of list

data = {
    'Name': ['Person1','Person2','Person3'],
    'Age': [20,30,40],
    'Location' : ['HYD','BLR','MAS']
}
dataframe = pd.DataFrame(data)
print(f"DataFrame obtained from dictionary of list values is : \n{dataframe}")
print(f"\nData type of DataFrame is : {type(dataframe)}")

DataFrame obtained from dictionary of list values is :
      Name  Age Location
0  Person1   20      HYD
1  Person2   30      BLR
2  Person3   40      MAS

Data type of DataFrame is : <class 'pandas.DataFrame'>

In [81]:
# Creating a dataframe from a list of dictionaries
data = [
    {
        'name':'Person1',
        'age':20,
        'location':'HYD'
    },
    {
        'name':'Person2',
        'age':30,
        'location':'BLR'
    },
    {
        'name':'Person3',
        'age':40,
        'location':'MAS'
    }
]

dataframe = pd.DataFrame(data)
print(f"Dataframe obtained from a list of dictionaries is : \n{dataframe}")

Dataframe obtained from a list of dictionaries is :
      name  age location
0  Person1   20      HYD
1  Person2   30      BLR
2  Person3   40      MAS

In [82]:
# Reading csv file

df = pd.read_csv('employees.csv')
print(f"First 5 rows of data is : \n{df.head(5)}")

First 5 rows of data is :
   id     name  age   department  salary
0   1    Alice   25           HR   50000
1   2      Bob   30  Engineering   70000
2   3  Charlie   28    Marketing   55000
3   4    Diana   35  Engineering   80000
4   5    Ethan   40      Finance   90000

### Accessing data from dataframe

In [83]:
# The dataframe is a 2-dimensional data structure
# When we get a single column from a dataset, it will be a series

print(f"The values in name column of dataframe is :\n{df['name']}")
print(f"The data type of name column in dataframe is : {type(df['name'])}")

The values in name column of dataframe is :
0      Alice
1        Bob
2    Charlie
3      Diana
4      Ethan
5      Fiona
6     George
7      Helen
Name: name, dtype: str
The data type of name column in dataframe is : <class 'pandas.Series'>

In [84]:
# Using loc
df.loc[0]

id                1
name          Alice
age              25
department       HR
salary        50000
Name: 0, dtype: object

In [85]:
# Using iloc
df.iloc[0]

id                1
name          Alice
age              25
department       HR
salary        50000
Name: 0, dtype: object

In [86]:
# Accessing a specified element using at
# Accessing name value from index 1 of dataframe

df.at[1,'name']

'Bob'

In [87]:
# Accessing a specified element like we do for multi-dimensional matrix using iat
# Accessing element at second row and second column of dataframe
df.iat[1,1]

'Bob'

### Data Manipulation

In [88]:
# Current dataframe

df

   id     name  age   department  salary
0   1    Alice   25           HR   50000
1   2      Bob   30  Engineering   70000
2   3  Charlie   28    Marketing   55000
3   4    Diana   35  Engineering   80000
4   5    Ethan   40      Finance   90000
5   6    Fiona   29           HR   52000
6   7   George   32    Marketing   60000
7   8    Helen   27      Finance   58000

In [89]:
# Adding location column data

df['Location'] = ['HYD','BLR','DEL','MUM','TPTY','VSP','CCT','MAS']
df

   id     name  age   department  salary Location
0   1    Alice   25           HR   50000      HYD
1   2      Bob   30  Engineering   70000      BLR
2   3  Charlie   28    Marketing   55000      DEL
3   4    Diana   35  Engineering   80000      MUM
4   5    Ethan   40      Finance   90000     TPTY
5   6    Fiona   29           HR   52000      VSP
6   7   George   32    Marketing   60000      CCT
7   8    Helen   27      Finance   58000      MAS

In [90]:
# Dropping a column in dataframe
# Axis = 1 checks for that particular column name while Axis = 0 will check for row index
# A normal drop is a temporary operation and will not effect original dataframe

print(f"When we drop the age column : \n{df.drop('age',axis = 1)}")
print(f"\nThe original dataframe : \n{df}")

When we drop the age column :
   id     name   department  salary Location
0   1    Alice           HR   50000      HYD
1   2      Bob  Engineering   70000      BLR
2   3  Charlie    Marketing   55000      DEL
3   4    Diana  Engineering   80000      MUM
4   5    Ethan      Finance   90000     TPTY
5   6    Fiona           HR   52000      VSP
6   7   George    Marketing   60000      CCT
7   8    Helen      Finance   58000      MAS

The original dataframe :
   id     name  age   department  salary Location
0   1    Alice   25           HR   50000      HYD
1   2      Bob   30  Engineering   70000      BLR
2   3  Charlie   28    Marketing   55000      DEL
3   4    Diana   35  Engineering   80000      MUM
4   5    Ethan   40      Finance   90000     TPTY
5   6    Fiona   29           HR   52000      VSP
6   7   George   32    Marketing   60000      CCT
7   8    Helen   27      Finance   58000      MAS

In [91]:
# To make drop permanent and persist in dataframe, we must use inplace = True

df.drop('age',axis=1,inplace=True)
print(f"\nOriginal dataframe is : \n{df}")

Original dataframe is :
   id     name   department  salary Location
0   1    Alice           HR   50000      HYD
1   2      Bob  Engineering   70000      BLR
2   3  Charlie    Marketing   55000      DEL
3   4    Diana  Engineering   80000      MUM
4   5    Ethan      Finance   90000     TPTY
5   6    Fiona           HR   52000      VSP
6   7   George    Marketing   60000      CCT
7   8    Helen      Finance   58000      MAS

In [92]:
# Incrementing everyone's salary by 15000

df['salary'] = df['salary'] + 15000
print(f"Dataframe after incrementing salary is : \n{df}")

Dataframe after incrementing salary is :
   id     name   department  salary Location
0   1    Alice           HR   65000      HYD
1   2      Bob  Engineering   85000      BLR
2   3  Charlie    Marketing   70000      DEL
3   4    Diana  Engineering   95000      MUM
4   5    Ethan      Finance  105000     TPTY
5   6    Fiona           HR   67000      VSP
6   7   George    Marketing   75000      CCT
7   8    Helen      Finance   73000      MAS

In [93]:
# Dropping a row
# As mentioned in the top, by default the axis parameter value will be 0 so the drop function will look at rows
# And to make change permanent we must add inplace=True otherwise it will not eb reflected in original db

df.drop(1,inplace=True)
print(f"DataFrame after dropping row with index 1 : \n{df}")

DataFrame after dropping row with index 1 :
   id     name   department  salary Location
0   1    Alice           HR   65000      HYD
2   3  Charlie    Marketing   70000      DEL
3   4    Diana  Engineering   95000      MUM
4   5    Ethan      Finance  105000     TPTY
5   6    Fiona           HR   67000      VSP
6   7   George    Marketing   75000      CCT
7   8    Helen      Finance   73000      MAS

### Summaries and Group by operations

In [95]:
grouped_mean = df.groupby('department')['salary'].mean()
print(f"Mean salaries of each individual department is : \n{grouped_mean}")

Mean salaries of each individual department is :
department
Engineering    95000.0
Finance        89000.0
HR             66000.0
Marketing      72500.0
Name: salary, dtype: float64

In [96]:
# Data types of each column

print(f"Data types of each column are: \n{df.dtypes}")

Data types of each column are:
id            int64
name            str
department      str
salary        int64
Location        str
dtype: object

In [98]:
# Describing dataframe

print(f"Statistical summary of dataframe is : \n{df.describe()}")

Statistical summary of dataframe is :
             id         salary
count  7.000000       7.000000
mean   4.857143   78571.428571
std    2.410295   15295.501984
min    1.000000   65000.000000
25%    3.500000   68500.000000
50%    5.000000   73000.000000
75%    6.500000   85000.000000
max    8.000000  105000.000000